secrets:
  db_user:
    file: /secrets/db_user.txt
  db_password:
    file: /secrets/db_password.txt

services:
  postgres:
    container_name: postgres_service
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER_FILE: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U social_media"]
      interval: 10s
      timeout: 30s
      retries: 3

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    container_name: smtp4dev_service
    ports:
      - "9090:80"
      - "25:25"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASSWORD=guest
  minio:
    container_name: minio
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Interface web

    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data: